accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path
from . import views

#namespaces so if there are other apps with 
#paths with the same name we will be taken to the correct url.
app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name = "list"),
    path('create/', views.article_create, name= "create"),
    path('<slug>/', views.article_detail, name = "detail")
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', article_views.article_list, name = "home"),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
#Create Models in this file.

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = RichTextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='hadley_logo.png', blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, default = None)

    #Controls what the object displays when viewed in the shell using ClassName.objects.all()
    #Instead of returning the object, returns the title.
    def __str__(self):
        return self.title

    

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in.
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
       form = AuthenticationForm(data=request.POST) 
       if form.is_valid():
           #log in the user.
           user = form.get_user()
           login(request, user)
           if 'next' in request.POST:
               return redirect(request.POST.get('next'))
           else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    #pulls all the article objects and orders them by date.
    articles = Article.objects.all().reverse().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>
        Log in
    </h1>
    <!-- Form baked into django auth system-->
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <!-- Form baked into django auth system-->
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="create-article">
    <h2>Create a New Article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}
        <input type="submit" value="Publish">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock%}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{%block content %}
    <div class="article-detail">
        <div class="article">
            <img src = "{{article.thumb.url}}"/>
            <h2>{{article.title|safe}}</h2>
            <p>{{article.body|safe}}</p>
            <p>{{article.date}}</p>
        </div>
    </div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{%block content %}
        <h1>Article List</h1>
        <div class="articles" >
            <!-- Python Code Template Tags-->
            <!-- To print python variables put them in double curly braces -->
            <!-- To write python code put it in curly brace percent sign (endfor endblock etc..) 
            -->
            {%for article in articles %}
                <div class="article">
                    <span>
                        <a href = "{% url 'articles:detail' slug=article.slug %}">
                        <h2>{{article.title}}</h2>
                        <p>{{article.snippet}}</p>
                        <p>{{article.date}}</p>
                        <p class="author"><a href = article_create.html></a>added by {{article.author.username}}</p>
                    </span>
                </div>
            {% endfor %}
        </div>
{% endblock %} 

templates/base_layout.html
<!-- This file is used for the content that will be on every page -->

<!-- Includes all static files. (CSS, images, etc.) -->
{% load static from static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset = "utf-8">
    <title>
        Hadley Digital
    </title>
    <!-- Better than hardcoding url -->
    <link rel="stylesheet" href = "{% static 'styles.css' %}">

    
</head>
<body>
    <header class="wrapper">
        <h1><a href="{% url 'articles:list' %}"><img src="{%static 'hadley_logo.png'%}"></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{%url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type = "submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create'%}" class="highlight">New Article</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login'%}">Login</a></li>
                    <li><a href="{% url 'accounts:signup'%}">Sign-Up</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">  
        {%block content %}

        {%endblock%}
    </div>

    <div class="footer">
        <div class="footer-left">
            <h2>Connections</h2>
            <p><strong><a href="https://www.github.com/nhadley1">Github</a></strong></p>
            <p><strong><a href="https://nhadley1.github.io/Portfolio">Personal Portfolio</a></strong></p>
        </div>

        <div class = "footer-middle">
            <a href="{% url 'articles:list' %}"><img src="{%static 'hadley_logo.png'%}" alt="Hadley-Digital"></a>
        </div>
    </div>
</body>

</html>